### ISSUE TITLE
CGI not  working

### ISSUE THREAD

**Issue by sanyaade-iot** [klange/cgiserver#3]
Hi Klange,

Thank you for put the cgiserver online. I compiled today on my Linux box, run cgiserver. The server runs on my localhost but it wont parse .php file, it spew out the script. Is it possible to add path to php interpreter instead of on pipe or socket?
That way we can use it for any cgi executable and make it more flexible and more generic.

Many thanks!

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by klange** [comment]
Did you:

1. Set the php script as executable?
2. Include a shebang (`#!/...`) to execute the php-cgi interpreter (eg. `#!/usr/bin/php-cgi`)?

These are both necessary steps. The server does not parse anything, it executes files which are marked as executable, or otherwise returns them raw.

```php
#!/usr/bin/php-cgi
<?php

echo "hello, world";
```

This is a pet project from nearly a decade ago, and I don't recommend using it at all - I haven't invested much of any time in ensuring it is secure or performant.

**Comment by sanyaade-iot** [comment]
Hi,

I am porting/compiling it for ESP8266 which is an embedded device with very low memory so I need to run a custom built php-cgi interpreter (PH7). 

shebang wont work as per no shell and it is flash memory based.

I think directive to the cgi-interpreter will do the trick

Many thanks for your quick reply

God blesses!!!

Best regards,
Sanyaade

**Comment by klange** [comment]
Shebangs generally aren't interpreted by shells, but by the kernel. If you have enough kernel support to run the threads, forking, pipes, signals, etc. necessary to use the server, you should be able to do shebangs. Alternatively, if you're only intending to run PHP, maybe just patch the server to call your php-cgi interpreter with the path to the script instead of calling the script directly.
